USE JUGOS_VENTAS;
SELECT * FROM FACTURAS;
SELECT * FROM TABLA_DE_CLIENTES; 
SELECT DNI, NOMBRE FROM TABLA_DE_CLIENTES;
SELECT DNI AS ID, NOMBRE AS CLIENTES FROM TABLA_DE_CLIENTES;
SELECT DNI AS ID, NOMBRE AS CLIENTES FROM TABLA_DE_CLIENTES WHERE NOMBRE = "JORGE";

