USE JUGOS_VENTAS;
SELECT DISTINCT BARRIO FROM TABLA_DE_VENDEDORES;
SELECT DISTINCT BARRIO FROM TABLA_DE_VENDEDORES;

SELECT DISTINCT BARRIO FROM TABLA_DE_CLIENTES
UNION
SELECT DISTINCT BARRIO FROM TABLA_DE_VENDEDORES;

SELECT DISTINCT BARRIO FROM TABLA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BARRIO FROM TABLA_DE_VENDEDORES;

SELECT DISTINCT BARRIO, NOMBRE, 'CLIENTE' AS TIPO FROM TABLA_DE_CLIENTES
UNION
SELECT DISTINCT BARRIO, NOMBRE, 'VENDEDOR' AS TIPO FROM TABLA_DE_VENDEDORES;

SELECT DISTINCT BARRIO, NOMBRE, 'CLIENTE' AS TIPO_CLIENTE FROM TABLA_DE_CLIENTES
UNION
SELECT DISTINCT BARRIO, NOMBRE, 'VENDEDOR' AS TIPO_VENDEDOR FROM TABLA_DE_VENDEDORES; 
/*EL SEGUNDO TIPO NO LO CONSIDERA, EL ALIAS SOLO LO TOMA DE LA PRIMERA INSTRUCCION EN ESTE CASO SOLO TOMA COMO TIPO CLIENTE EL ALIAS*/


