USE JUGOS_VENTAS;
SELECT * FROM TABLA_DE_PRODUCTOS WHERE SABOR ='MANGO' AND TAMANO='470 ML';

SELECT * FROM TABLA_DE_PRODUCTOS WHERE NOT (SABOR='MANGO') OR TAMANO='470 ML';

SELECT * FROM TABLA_DE_PRODUCTOS WHERE SABOR ='MANGO' AND  NOT (TAMANO='470 ML'); 

SELECT * FROM TABLA_DE_PRODUCTOS WHERE SABOR IN ('MANGO', 'UVA');
SELECT * FROM tabla_de_clientes;
SELECT * FROM tabla_de_clientes WHERE CIUDAD IN ('Ciudad de México', 'Guadalajara') AND edad > 21;
SELECT * FROM tabla_de_clientes WHERE ciudad IN ('ciudad de México', 'Guadalajara') AND (edad BETWEEN 20 AND 30);

SELECT * FROM FACTURAS;
SELECT * FROM ITEMS_FACTURAS;
SELECT * FROM ITEMS_FACTURAS WHERE CANTIDAD > 60 AND PRECIO <= 3;