USE JUGOS_VENTAS;
SELECT * FROM TABLA_DE_PRODUCTOS ORDER BY PRECIO_DE_LISTA;

SELECT ESTADO, sum(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM TABLA_DE_CLIENTES GROUP BY ESTADO;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS MAYOR_PRECIO FROM TABLA_DE_PRODUCTOS GROUP BY ENVASE;

SELECT ENVASE, COUNT(*) FROM TABLA_DE_PRODUCTOS GROUP BY ENVASE;

SELECT BARRIO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM TABLA_DE_CLIENTES GROUP BY BARRIO;
SELECT CIUDAD, BARRIO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM TABLA_DE_CLIENTES WHERE CIUDAD = 'CIUDAD DE MÉXICO' GROUP BY BARRIO;

SELECT CIUDAD, BARRIO, SUM(LIMITE_DE_CREDITO) AS TOTAL FROM TABLA_DE_CLIENTES WHERE CIUDAD = 'GUADALAJARA' group by ESTADO, BARRIO;

SELECT CIUDAD, BARRIO, MAX(LIMITE_DE_CREDITO) AS LIMITE FROM TABLA_DE_CLIENTES GROUP BY CIUDAD, BARRIO;

SELECT ESTADO, BARRIO, MAX(LIMITE_DE_CREDITO) 
AS LIMITE, MAX(EDAD) 
AS EDAD 
FROM TABLA_DE_CLIENTES 
WHERE EDAD >=20 
GROUP BY ESTADO, BARRIO 
ORDER BY EDAD;

SELECT ESTADO, BARRIO, MAX(LIMITE_DE_CREDITO) AS LIMITE, MAX(EDAD) AS EDAD
FROM tabla_de_clientes
WHERE EDAD >= 20
GROUP BY ESTADO, BARRIO
ORDER BY EDAD;
