SELECT * FROM tbproducto;

SELECT * FROM tbproducto WHERE PRECIO_LISTA BETWEEN 28 AND 29;

SELECT * FROM tbproducto WHERE ENVASE = 'LATA' OR ENVASE = 'BOTELLA PET';

SELECT * FROM tbproducto WHERE ENVASE = 'LATA' OR ENVASE = 'BOTELLA PET' ORDER BY ENVASE;

SELECT * FROM tbproducto WHERE (PRECIO_LISTA >= 15 AND TAMANO = '1 LITRO') OR (ENVASE = 'LATA' OR ENVASE = 'BOTELLA PET') ORDER BY NOMBRE;
SELECT * FROM tbproducto WHERE (PRECIO_LISTA >= 15 AND TAMANO = '1 LITRO') OR (ENVASE = 'LATA' OR ENVASE = 'BOTELLA PET') ORDER BY ENVASE;