SELECT * FROM tbcliente;
SELECT * FROM tbcliente WHERE FECHA_NACIMIENTO BETWEEN 1995-01-01 AND 2000-01-01;

SELECT * FROM tbcliente WHERE YEAR (FECHA_NACIMIENTO) = 1995;
SELECT * FROM tbcliente WHERE MONTH (FECHA_NACIMIENTO) = 1;
