SELECT * FROM tbcliente;

SELECT * FROM tbcliente WHERE EDAD > 27;
SELECT * FROM tbcliente WHERE EDAD >= 20;

SELECT * FROM TBCLIENTE WHERE CIUDAD = 'CIUDAD DE MEXICO';
SELECT * FROM tbcliente WHERE NOMBRE > 'ERICA CARVAJO';
SELECT * FROM tbcliente WHERE NOMBRE < 'ERICA CARVAJO';
SELECT * FROM tbcliente WHERE NOMBRE >= 'ERICA CARVAJO';

SELECT * FROM tbproducto;
SELECT * FROM tbproducto WHERE PRECIO_LISTA = 28.51;
SELECT * FROM tbproducto WHERE PRECIO_LISTA BETWEEN 28.49 AND 28.52;
SELECT * FROM tbproducto WHERE PRECIO_LISTA BETWEEN 10 AND 50;
