USE JUGOS;
SELECT * FROM tbproducto;
SELECT * FROM TBPRODUCTO WHERE SABOR = 'MARACUYÁ';
SELECT * FROM TBPRODUCTO WHERE ENVASE = 'BOTELLA DE VIDRIO';

UPDATE TBPRODUCTO SET SABOR = 'CITRICO' WHERE SABOR = 'LIMON';
SELECT * FROM TBPRODUCTO WHERE SABOR = 'CITRICO';
